"""
Django settings for PyTime_Project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.conf.global_settings import ALLOWED_HOSTS
import environ
from os import path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load Env
env = environ.Env()
environ.Env.read_env(path.join(BASE_DIR.parent, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(env('DEBUG'))

ALLOWED_HOSTS = [
    *env('ALLOWED_HOSTS').split()
] + ['192.168.0.164']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bleach',
    'ckeditor',
    'ckeditor_uploader',
    'apps.core',
    'apps.users',
    'apps.tags',
    'apps.skills',
    'apps.articles',
    'apps.projects',
    'apps.comments',
    'apps.likes',
]

AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'PyTime_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PyTime_Project.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env('HOST'),
        "PORT": env('DB_PORT_DEV') if DEBUG else env('DB_PORT_PROD'),
        "NAME": env('DB_NAME_DEV') if DEBUG else env('DB_NAME_PROD'),
        "USER": env('DB_USER_DEV') if DEBUG else env('DB_USER_PROD'),
        "PASSWORD": env('DB_PASSWORD_DEV') if DEBUG else env('DB_PASSWORD_PROD'),
        'TEST': {
            'NAME': 'testing_' + env('DB_NAME_DEV') if DEBUG else env('DB_NAME_PROD'),
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# For HTTPS settings
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [
        'https://pytime.ru',
        'https://www.pytime.ru',
    ]
    CSRF_COOKIE_DOMAIN = '.pytime.ru'
    SESSION_COOKIE_DOMAIN = '.pytime.ru'



# CKEditor settgins
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "ckeditorUpload/"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_PyTimeAdminConfig': [
            {
                'name': 'document',
                'items': [
                    'Source', '-',
                    'Save', 'Preview',
                ]
            },
            {
                'name': 'clipboard',
                'items': [
                    'Cut', 'Copy', 'Paste', 'PasteText', '-',
                    'Undo', 'Redo',
                ]
            },
            {
                'name': 'editing',
                'items': [
                    'Find', 'Replace',
                ]
            },
            {
                'name': 'paragraph',
                'items': [
                    'BidiLtr', 'BidiRtl',
                ]
            },
            {
                'name': 'tools',
                'items': [
                    'Maximize', 'ShowBlocks', '-',
                ]
            },
            {
                'name': 'basicstyles',
                'items': [
                    'RemoveFormat',
                ]
            },
            '/',
            {
                'name': 'styles',
                'items': [
                    'Styles', 'Format',
                ]
            },
            {
                'name': 'colors',
                'items': [
                    'TextColor', 'BGColor',
                ]
            },
            {
                'name': 'basicstyles',
                'items': [
                    'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript',
                ]
            },
            {
                'name': 'paragraph',
                'items': [
                    'NumberedList', 'BulletedList', '-',
                    'Outdent', 'Indent', '-',
                    'Blockquote', 'CodeSnippet', 'CreateDiv', '-',
                    'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-',
                ]
            },
            {
                'name': 'links',
                'items': [
                    'Link', 'Unlink', 'Anchor',
                ]
            },
            {
                'name': 'insert',
                'items': [
                    'Image', 'Flash', 'Table', 'HorizontalRule', 'SpecialChar',
                ]
            },
        ],
        'toolbar': 'PyTimeAdminConfig',
        'autoGrow_onStartup': True,
        'autoGrow_maxHeight': '500',
        'enterMode': 1,
        'shiftEnterMode': 3,
        'clipboard_handleImages': False,
        "removePlugins": "exportpdf",
        'extraPlugins': ','.join([
            'codesnippet',
            'placeholder',
            'autogrow',
            'scayt',
        ]),
        'codeSnippet_theme': 'monokai'
    },
}

CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_DATE = True



# Bleach settings
BLEACH_ALLOWED_TAGS = []
BLEACH_ALLOWED_ATTRIBUTES = []
BLEACH_ALLOWED_STYLES = []
BLEACH_ALLOWED_PROTOCOLS = []
BLEACH_STRIP_TAGS = True
BLEACH_STRIP_COMMENTS = True
