
services:
  database:
    image: postgres:16.9-alpine
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pytime:
    build:
      context: ./PyTime_Project
    container_name: PyTime
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - static_volume:/core/static


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    depends_on:
      - pytime
      - database

volumes:
  postgres_data:
  static_volume:
