# Generated by Django 5.1.7 on 2025-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('ARTICLE', 'article'), ('PROJECT', 'project')], max_length=7, verbose_name='Тип контента'),
        ),
    ]
