# Generated by Django 5.1.7 on 2025-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_datetimecreate_tag_datetimeupdate_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
