# Generated by Django 5.1.7 on 2025-04-12 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_article_description_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datetimeCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='datetimeUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='shortTitle',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projectTags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
