# Generated by Django 5.1.7 on 2025-07-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hardskillscategory_visiblehardskills_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisibleHardSkills',
            new_name='VisibleHardSkillsCategoryManager',
        ),
        migrations.RenameModel(
            old_name='VisibleHardSkillsCategory',
            new_name='VisibleHardSkillsManager',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='hardskills',
            options={'verbose_name': 'Hard скилл', 'verbose_name_plural': 'Hard скиллы'},
        ),
        migrations.AlterModelOptions(
            name='hardskillscategory',
            options={'verbose_name': 'Категория Hard скилла', 'verbose_name_plural': 'Категории Hard скиллов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
