# Generated by Django 5.1.7 on 2025-07-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_visiblehardskills_visiblehardskillscategorymanager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisibleHardSkillsCategoryManager',
        ),
    ]
