# Generated by Django 5.1.7 on 2025-07-09 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_visiblehardskillscategorymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisibleHardSkillsManager',
        ),
        migrations.AlterModelOptions(
            name='hardskills',
            options={'verbose_name': 'Скилл', 'verbose_name_plural': 'Скиллы'},
        ),
        migrations.RemoveField(
            model_name='hardskills',
            name='category',
        ),
        migrations.AddField(
            model_name='hardskills',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardskillscategory',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardskillscategory',
            name='skills',
            field=models.ManyToManyField(default='Отсутствует', to='core.hardskills'),
        ),
    ]
