# Generated by Django 5.1.7 on 2025-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_visiblehardskillsmanager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardskillscategory',
            options={'verbose_name': 'Категория скилла', 'verbose_name_plural': 'Категории скиллов'},
        ),
        migrations.AddField(
            model_name='hardskillscategory',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hardskillscategory',
            name='skills',
            field=models.ManyToManyField(to='core.hardskills'),
        ),
    ]
