# Generated by Django 5.1.7 on 2025-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_hardskillscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskillscategory',
            name='position',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
