# Generated by Django 5.1.7 on 2025-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_hardskillscategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskillscategory',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.hardskills'),
        ),
    ]
