# Generated by Django 5.1.7 on 2025-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_hardskillscategory_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskillscategory',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
