# Generated by Django 5.1.7 on 2025-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hardskillscategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskillscategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
