# Generated by Django 5.1.7 on 2025-08-13 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentSlug', models.SlugField(verbose_name='Slug контента')),
                ('contentType', models.CharField(choices=[('ARTICLE', 'article'), ('PROJECT', 'project')], max_length=7, verbose_name='Тип контента')),
                ('text', models.TextField(verbose_name='Текст')),
                ('isVisible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikesComment', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(blank=True, related_name='likesComment', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyComment', to='comments.comment', verbose_name='Ответы на комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
