# Generated by Django 5.1.7 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='replyComment', to='comments.comment', verbose_name='Ответы на комментарий'),
        ),
    ]
