# Generated by Django 5.1.7 on 2025-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_reply_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isReply',
            field=models.BooleanField(default=False, verbose_name='Является ответом'),
        ),
    ]
