# Generated by Django 5.1.7 on 2025-08-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_isreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parent', to='comments.comment', verbose_name='Комментарий родитель'),
        ),
        migrations.AddField(
            model_name='comment',
            name='toWhomReply',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='toWhomReply', to=settings.AUTH_USER_MODEL, verbose_name='Кому ответ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorComments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
