# Generated by Django 5.1.7 on 2025-08-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('isVisible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
            },
        ),
        migrations.CreateModel(
            name='HardSkillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('isVisible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('skills', models.ManyToManyField(blank=True, to='skills.hardskills')),
            ],
            options={
                'verbose_name': 'Категория скилла',
                'verbose_name_plural': 'Категории скиллов',
            },
        ),
    ]
