events {}

http {
    # HTTP
    server {
        listen 80;
        server_name www.pytime.ru pytime.ru admin.pytime.ru dev.pytime.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Редирект с www на без www (для HTTP)
        if ($host = www.pytime.ru) {
            return 301 https://$host$request_uri;
        }

        return 301 https://$host$request_uri;
    }

    # HTTPS сервер для редиректа www -> без www
    server {
        listen 443 ssl;
        server_name www.pytime.ru;

        ssl_certificate /etc/letsencrypt/live/pytime.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pytime.ru/privkey.pem;

        return 301 https://$host$request_uri;
    }

    # Основной HTTPS сервер
    server {
        listen 443 ssl;
        server_name pytime.ru;

        ssl_certificate /etc/letsencrypt/live/pytime.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pytime.ru/privkey.pem;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline'" always;

        location / {
            proxy_pass http://core:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ /\.git {
            deny all;
            return 403;
        }

        location /static/ {
            alias /static/;
            include /etc/nginx/mime.types;
        }
    }

    # Поддомены HTTPS сервера
    server {
        listen 443 ssl;
        server_name admin.pytime.ru dev.pytime.ru;

        ssl_certificate /etc/letsencrypt/live/pytime.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pytime.ru/privkey.pem;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline'" always;

        location / {
            proxy_pass http://core:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ /\.git {
            deny all;
            return 403;
        }

        location /static/ {
            alias /static/;
            include /etc/nginx/mime.types;
        }
    }
}