# Generated by Django 5.1.7 on 2025-08-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectslikes',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectslikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleLikes',
        ),
        migrations.DeleteModel(
            name='ProjectsLikes',
        ),
    ]
