# Generated by Django 5.1.7 on 2025-08-11 09:40

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gitLink',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aboutMe',
            field=django_bleach.models.BleachField(blank=True, max_length=255, null=True, verbose_name='Обо мне'),
        ),
    ]
