# Generated by Django 5.1.7 on 2025-08-11 09:41

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_gitlink_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aboutMe',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=255, null=True, verbose_name='Обо мне'),
        ),
    ]
