# Generated by Django 5.1.7 on 2025-08-11 15:45

import django.db.models.deletion
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=django_bleach.models.BleachField(default='Anonymous', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=django_bleach.models.BleachField(default='User', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profileavatarmodel', verbose_name='Аватар Пользователя'),
        ),
    ]
