# Generated by Django 5.1.7 on 2025-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profileavatarmodel_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.FileField(upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
