# Generated by Django 5.1.7 on 2025-08-11 16:47

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profileavatarmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=django_bleach.models.BleachField(blank=True, default='Anonymous', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=django_bleach.models.BleachField(blank=True, default='User', max_length=100, verbose_name='Фамилия'),
        ),
    ]
