# Generated by Django 5.1.7 on 2025-08-12 07:40

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profileavatarmodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatarmodel',
            name='avatarGenerate',
            field=models.ImageField(default='users/img/avatars/default.svg', upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.ImageField(upload_to='avatars/users/', verbose_name='Аватар'),
        ),
    ]
