# Generated by Django 5.1.7 on 2025-08-12 07:42

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profileavatarmodel_avatargenerate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileavatarmodel',
            name='avatarGenerate',
        ),
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.ImageField(default='users/img/avatars/default.svg', upload_to='avatars/users/', verbose_name='Аватар'),
        ),
    ]
