# Generated by Django 5.1.7 on 2025-08-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profileavatarmodel_avatargenerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profileavatarmodel', verbose_name='Аватар Пользователя'),
        ),
    ]
