# Generated by Django 5.1.7 on 2025-08-12 08:49

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatarmodel',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profileavatarmodel', verbose_name='Аватар Пользователя'),
        ),
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.ImageField(upload_to='avatars/users/', verbose_name='Аватар'),
        ),
    ]
