# Generated by Django 5.1.7 on 2025-08-12 08:55

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profileavatarmodel_isdefault_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.ImageField(default='avatars/generate/default.svg', upload_to='avatars/users/', verbose_name='Аватар'),
        ),
    ]
