# Generated by Django 5.1.7 on 2025-08-12 14:32

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarmodel',
            name='avatar',
            field=models.FileField(default='avatars/generate/default.svg', upload_to='avatars/users/', verbose_name='Аватар'),
        ),
    ]
