# Generated by Django 5.1.7 on 2025-08-18 14:04

import apps.users.utils
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profileavatarmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=80, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=80, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=apps.users.utils.UserModelUtils.get, max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
