# Generated by Django 5.1.7 on 2025-08-18 14:05

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aboutMe',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=255, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=80, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=django_bleach.models.BleachField(blank=True, default='', max_length=80, verbose_name='Фамилия'),
        ),
    ]
