# Generated by Django 5.1.7 on 2025-08-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userverificationcode_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVerificationCode',
            new_name='EmailVerification',
        ),
    ]
