# Generated by Django 5.1.7 on 2025-08-05 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_shorttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
