# Generated by Django 5.1.7 on 2025-08-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('shortTitle', models.CharField(max_length=50, verbose_name='Краткий заголовок')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение')),
                ('datetimeCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetimeUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Видимость')),
                ('tags', models.ManyToManyField(blank=True, related_name='articleTags', to='tags.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
