# Generated by Django 5.1.7 on 2025-08-05 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='shortTitle',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
